package:
    name: elog
    version: 1.3.2
source:
    path: ..

requirements:
    build:
        - setuptools
        - python
        - passlib
        - requests
    run:
        - python
        - passlib
        - requests
        - lxml

about:
    home: https://git.psi.ch/cosylab/py_elog
    summary: "Interface to electronic logbooks elog."
